name: deployTslCert

pool:
  vmImage: ubuntu-latest
 
variables:
  - group: PipelineDeploymentVariables
  - name: filePath
    value: '$(System.DefaultWorkingDirectory)/pipelined/download-az-acme.ps1'

stages:
  - stage: certProcessing
    displayName: 'SSL Cert Processins'
    jobs:
      - job: getSetCert
        displayName: 'Get and set certicficate'
        steps:
          - task: PowerShell@2
            displayName: 'Get az-acme CLI'
            inputs:
              targetType: filePath
              filePath: $(filePath)