name: deployTslCert

trigger: none

pool:
  vmImage: ubuntu-latest
 
variables:
  - group: PipelineDeploymentVariables
  - name: filePath
    value: '$(System.DefaultWorkingDirectory)/pipelines/download-az-acme.ps1'
  - name: downloadedFile
    value: '$(System.DefaultWorkingDirectory)/cli-v0.3-win-x64.zip'

stages:
  - stage: certProcessing
    displayName: 'SSL Cert Processing'
    jobs:
      - job: getSetCert
        displayName: 'Get and set certificate'
        steps:
          - task: PowerShell@2
            displayName: 'Get az-acme CLI'
            inputs:
              targetType: filePath
              filePath: $(filePath)
              arguments: >
                - downloadedFile $(downloadedFile)
                - defaultWorkingDirectory $(System.DefaultWorkingDirectory)
          - bash: ls
            displayName: 'Test Az-Acme'
