name: buildAndDeployPipeline

trigger: none

pool:
  vmImage: ubuntu-latest
 
variables:
  - group: PipelineDeploymentVariables
  - name: templateFile
    value: '$(System.DefaultWorkingDirectory)/arm-templates/main.bicep'
  
stages:
  - stage: deployAzureResoures
    displayName: 'Deploy Azure Resources'
    jobs:
      - job: executeArmTemplate
        displayName: 'Execute ARM template'
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Template Deployment'
            inputs:
              deploymentScope: 'Subscription'
              deploymentMode: 'Incremental'
              azureResourceManagerConnection: $(azureResourceManagerConnection)
              action: 'Create Or Update Resource Group'
              location: 'northcentralus'
              templateLocation: 'Linked artifact'
              csmFile: $(templateFile)
              deploymentName: 'henderson-consulting-deployment-$(Build.BuildId)'

  
