name: hendeson-consulting-iac
run-name: ${{github.actor}} is building Henderson Consulting infrastructure
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@main