name: hendeson-consulting-resource-group-deployment
run-name: ${{github.actor}} is building Henderson Consulting infrastructure
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
           node-version: 'lts/*'
      - run: npm install -g bats
      - run: bats -v 